apiVersion: apps/v1
kind: Deployment 
metadata:
  name: stedi-sam-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stedi-sam-dev
  template:
    metadata:
      labels:
        app: stedi-sam-dev
    spec:
      containers:
        - name: stedi-sam-dev
          image: gcr.io/cheese-empanadas/sam-stedi-api
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets-sam
                  key: REDIS_PASSWORD
            - name: REDIS_HOST
              value: "redis-stedi-prod"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: KAFKA_BROKER
              value: "localhost:9092"
          ports:
            - containerPort: 443
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 4567
            initialDelaySeconds: 10
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: stedi-sam-nodeport
spec:
  selector:
    app: stedi-sam-dev
  type: NodePort
  ports:
  - port: 80
    targetPort: 4567
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: stedi-sam-certificate
spec:
  domains:
    - sam.cit262.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stedi-sam-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: stedi-sam-public
    networking.gke.io/managed-certificates: stedi-sam-certificate
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stedi-sam-nodeport
            port:
              number: 80